package com.android.systemui.statusbar.policy;

import com.android.systemui.R;
import com.android.systemui.statusbar.policy.MobileSignalController;
import java.util.HashMap;
import java.util.Map;

/* loaded from: classes.dex */
class TelephonyIcons {
    static final MobileSignalController.MobileIconGroup CARRIER_NETWORK_CHANGE;
    static final MobileSignalController.MobileIconGroup DATA_DISABLED;
    static final MobileSignalController.MobileIconGroup E;
    static final int FLIGHT_MODE_ICON = R.drawable.stat_sys_airplane_mode;
    static final MobileSignalController.MobileIconGroup FOUR_G;
    static final MobileSignalController.MobileIconGroup FOUR_G_PLUS;
    static final MobileSignalController.MobileIconGroup G;
    static final MobileSignalController.MobileIconGroup H;
    static final MobileSignalController.MobileIconGroup H_PLUS;
    static final int ICON_1X;
    static final int ICON_3G;
    static final int ICON_4G;
    static final int ICON_4G_PLUS;
    static final int ICON_5G;
    static final int ICON_5G_E;
    static final int ICON_5G_NSA;
    static final int ICON_5G_PLUS;
    static final int ICON_E;
    static final int ICON_G;
    static final int ICON_H;
    static final int ICON_H_PLUS;
    static final int ICON_LTE;
    static final int ICON_LTE_PLUS;
    static final Map<String, MobileSignalController.MobileIconGroup> ICON_NAME_TO_ICON;
    static final int ICON_VOWIFI;
    static final int ICON_VOWIFI_ASUS;
    static final int ICON_VOWIFI_CALLING;
    static final int ICON_VOWIFI_EMUI;
    static final int ICON_VOWIFI_MOTO;
    static final int ICON_VOWIFI_ONEPLUS;
    static final int ICON_VOWIFI_ONEPLUS_COMPACT;
    static final MobileSignalController.MobileIconGroup LTE;
    static final MobileSignalController.MobileIconGroup LTE_CA_5G_E;
    static final MobileSignalController.MobileIconGroup LTE_PLUS;
    static final MobileSignalController.MobileIconGroup NOT_DEFAULT_DATA;
    static final MobileSignalController.MobileIconGroup NR_5G;
    static final MobileSignalController.MobileIconGroup NR_5G_PLUS;
    static final MobileSignalController.MobileIconGroup NR_NSA;
    static final MobileSignalController.MobileIconGroup NR_SA;
    static final MobileSignalController.MobileIconGroup ONE_X;
    static final MobileSignalController.MobileIconGroup THREE_G;
    static final MobileSignalController.MobileIconGroup UNKNOWN;
    static final MobileSignalController.MobileIconGroup VOWIFI;
    static final MobileSignalController.MobileIconGroup VOWIFI_ASUS;
    static final MobileSignalController.MobileIconGroup VOWIFI_CALLING;
    static final MobileSignalController.MobileIconGroup VOWIFI_EMUI;
    static final MobileSignalController.MobileIconGroup VOWIFI_MOTO;
    static final MobileSignalController.MobileIconGroup VOWIFI_ONEPLUS;
    static final MobileSignalController.MobileIconGroup VOWIFI_ONEPLUS_COMPACT;
    static final MobileSignalController.MobileIconGroup WFC;

    static {
        int i = R.drawable.ic_lte_mobiledata;
        ICON_LTE = i;
        int i2 = R.drawable.ic_lte_plus_mobiledata;
        ICON_LTE_PLUS = i2;
        int i3 = R.drawable.ic_g_mobiledata;
        ICON_G = i3;
        int i4 = R.drawable.ic_e_mobiledata;
        ICON_E = i4;
        int i5 = R.drawable.ic_h_mobiledata;
        ICON_H = i5;
        int i6 = R.drawable.ic_h_plus_mobiledata;
        ICON_H_PLUS = i6;
        int i7 = R.drawable.ic_3g_mobiledata;
        ICON_3G = i7;
        int i8 = R.drawable.ic_4g_mobiledata;
        ICON_4G = i8;
        int i9 = R.drawable.ic_4g_plus_mobiledata;
        ICON_4G_PLUS = i9;
        int i10 = R.drawable.ic_5g_e_mobiledata;
        ICON_5G_E = i10;
        int i11 = R.drawable.ic_1x_mobiledata;
        ICON_1X = i11;
        int i12 = R.drawable.ic_5g_mobiledata;
        ICON_5G = i12;
        ICON_5G_NSA = R.drawable.ic_5g_nsa_mobiledata;
        int i13 = R.drawable.ic_5g_plus_mobiledata;
        ICON_5G_PLUS = i13;
        int i14 = R.drawable.ic_vowifi;
        ICON_VOWIFI = i14;
        int i15 = R.drawable.ic_vowifi_calling;
        ICON_VOWIFI_CALLING = i15;
        int i16 = R.drawable.ic_vowifi_asus;
        ICON_VOWIFI_ASUS = i16;
        int i17 = R.drawable.ic_vowifi_moto;
        ICON_VOWIFI_MOTO = i17;
        int i18 = R.drawable.ic_vowifi_oneplus;
        ICON_VOWIFI_ONEPLUS = i18;
        int i19 = R.drawable.ic_vowifi_emui;
        ICON_VOWIFI_EMUI = i19;
        int i20 = R.drawable.ic_vowifi_oneplus_compact;
        ICON_VOWIFI_ONEPLUS_COMPACT = i20;
        int[] iArr = AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH;
        MobileSignalController.MobileIconGroup mobileIconGroup = new MobileSignalController.MobileIconGroup("CARRIER_NETWORK_CHANGE", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.carrier_network_change_mode, 0, false);
        CARRIER_NETWORK_CHANGE = mobileIconGroup;
        MobileSignalController.MobileIconGroup mobileIconGroup2 = new MobileSignalController.MobileIconGroup("3G", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_3g, i7, true);
        THREE_G = mobileIconGroup2;
        MobileSignalController.MobileIconGroup mobileIconGroup3 = new MobileSignalController.MobileIconGroup("WFC", null, null, iArr, 0, 0, 0, 0, iArr[0], 0, 0, false);
        WFC = mobileIconGroup3;
        MobileSignalController.MobileIconGroup mobileIconGroup4 = new MobileSignalController.MobileIconGroup("Unknown", null, null, iArr, 0, 0, 0, 0, iArr[0], 0, 0, false);
        UNKNOWN = mobileIconGroup4;
        MobileSignalController.MobileIconGroup mobileIconGroup5 = new MobileSignalController.MobileIconGroup("E", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_edge, i4, false);
        E = mobileIconGroup5;
        MobileSignalController.MobileIconGroup mobileIconGroup6 = new MobileSignalController.MobileIconGroup("1X", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_cdma, i11, true);
        ONE_X = mobileIconGroup6;
        MobileSignalController.MobileIconGroup mobileIconGroup7 = new MobileSignalController.MobileIconGroup("G", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_gprs, i3, false);
        G = mobileIconGroup7;
        MobileSignalController.MobileIconGroup mobileIconGroup8 = new MobileSignalController.MobileIconGroup("H", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_3_5g, i5, false);
        H = mobileIconGroup8;
        MobileSignalController.MobileIconGroup mobileIconGroup9 = new MobileSignalController.MobileIconGroup("H+", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_3_5g_plus, i6, false);
        H_PLUS = mobileIconGroup9;
        MobileSignalController.MobileIconGroup mobileIconGroup10 = new MobileSignalController.MobileIconGroup("4G", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_4g, i8, true);
        FOUR_G = mobileIconGroup10;
        MobileSignalController.MobileIconGroup mobileIconGroup11 = new MobileSignalController.MobileIconGroup("4G+", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_4g_plus, i9, true);
        FOUR_G_PLUS = mobileIconGroup11;
        MobileSignalController.MobileIconGroup mobileIconGroup12 = new MobileSignalController.MobileIconGroup("LTE", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_lte, i, true);
        LTE = mobileIconGroup12;
        MobileSignalController.MobileIconGroup mobileIconGroup13 = new MobileSignalController.MobileIconGroup("LTE+", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_lte_plus, i2, true);
        LTE_PLUS = mobileIconGroup13;
        MobileSignalController.MobileIconGroup mobileIconGroup14 = new MobileSignalController.MobileIconGroup("5Ge", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_5ge_html, i10, true);
        LTE_CA_5G_E = mobileIconGroup14;
        MobileSignalController.MobileIconGroup mobileIconGroup15 = new MobileSignalController.MobileIconGroup("5G", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_5g, i12, true);
        NR_5G = mobileIconGroup15;
        MobileSignalController.MobileIconGroup mobileIconGroup16 = new MobileSignalController.MobileIconGroup("5G_PLUS", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_5g_plus, i13, true);
        NR_5G_PLUS = mobileIconGroup16;
        NR_NSA = new MobileSignalController.MobileIconGroup("5G_NSA", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_5g_nsa, i12, true);
        NR_SA = new MobileSignalController.MobileIconGroup("5G_SA", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.data_connection_5g_sa, i13, true);
        MobileSignalController.MobileIconGroup mobileIconGroup17 = new MobileSignalController.MobileIconGroup("DataDisabled", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.cell_data_off_content_description, 0, false);
        DATA_DISABLED = mobileIconGroup17;
        MobileSignalController.MobileIconGroup mobileIconGroup18 = new MobileSignalController.MobileIconGroup("NotDefaultData", null, null, iArr, 0, 0, 0, 0, iArr[0], R.string.not_default_data_content_description, 0, false);
        NOT_DEFAULT_DATA = mobileIconGroup18;
        VOWIFI = new MobileSignalController.MobileIconGroup("VoWIFI", null, null, iArr, 0, 0, 0, 0, iArr[0], 0, i14, false);
        VOWIFI_CALLING = new MobileSignalController.MobileIconGroup("VoWIFICall", null, null, iArr, 0, 0, 0, 0, iArr[0], 0, i15, false);
        VOWIFI_MOTO = new MobileSignalController.MobileIconGroup("VoWIFI_Moto", null, null, iArr, 0, 0, 0, 0, iArr[0], 0, i17, false);
        VOWIFI_ASUS = new MobileSignalController.MobileIconGroup("VoWIFI_ASUS", null, null, iArr, 0, 0, 0, 0, iArr[0], 0, i16, false);
        VOWIFI_ONEPLUS = new MobileSignalController.MobileIconGroup("VoWIFI_OnePlus", null, null, iArr, 0, 0, 0, 0, iArr[0], 0, i18, false);
        VOWIFI_EMUI = new MobileSignalController.MobileIconGroup("VoWIFI_Emui", null, null, iArr, 0, 0, 0, 0, iArr[0], 0, i19, false);
        VOWIFI_ONEPLUS_COMPACT = new MobileSignalController.MobileIconGroup("VoWIFI_Oneplus_Compact", null, null, iArr, 0, 0, 0, 0, iArr[0], 0, i20, false);
        HashMap map = new HashMap();
        ICON_NAME_TO_ICON = map;
        map.put("carrier_network_change", mobileIconGroup);
        map.put("3g", mobileIconGroup2);
        map.put("wfc", mobileIconGroup3);
        map.put("unknown", mobileIconGroup4);
        map.put("e", mobileIconGroup5);
        map.put("1x", mobileIconGroup6);
        map.put("g", mobileIconGroup7);
        map.put("h", mobileIconGroup8);
        map.put("h+", mobileIconGroup9);
        map.put("4g", mobileIconGroup10);
        map.put("4g+", mobileIconGroup11);
        map.put("5ge", mobileIconGroup14);
        map.put("lte", mobileIconGroup12);
        map.put("lte+", mobileIconGroup13);
        map.put("5g", mobileIconGroup15);
        map.put("5g_plus", mobileIconGroup16);
        map.put("datadisable", mobileIconGroup17);
        map.put("notdefaultdata", mobileIconGroup18);
    }
}
